use_frameworks!

target 'SlideMenuDovi_Example' do
  pod 'SlideMenuDovi', :path => '../'

  target 'SlideMenuDovi_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
