# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift

def libs_test
    pod 'Quick', '~> 0.9.3'
    pod 'Nimble', '~> 4.1'
    pod 'KIF', '~> 3.5'
end

def swiftVersion
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '2.3'
            end
        end
    end
end

target 'SlideMenuDovi' do
    use_frameworks!
    
    target 'SlideMenuDoviTests' do
        inherit! :search_paths
        
        libs_test
    end
    
    swiftVersion
end


