sudo: false
language: objective-c
osx_image: xcode8

before_install:
  - gem install bundler

script:
  - bundle exec pod repo update --project-directory=Example
  - bundle exec pod install --project-directory=Example
  - xcodebuild -configuration Debug -workspace Example/SlideMenuDovi.xcworkspace -scheme SlideMenuDovi -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10.0' build test | xcpretty

# after_success:
#   - bundle exec slather

# language: objective-c
# osx_image: xcode7.3
#
# script: ./run_test.sh
