sudo: false
language: objective-c
osx_image: xcode7.3

before_install:
  - gem install bundler
  - pod install --project-directory=Example

script:
  - set -o pipefail && xcodebuild test -configuration Debug -workspace Example/SlideMenuDovi.xcworkspace -scheme SlideMenuDovi -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.3' | xcpretty -c

after_success: slather

# language: objective-c
# osx_image: xcode7.3
#
# script: ./run_test.sh
