sudo: false
language: objective-c
osx_image: xcode7.3
cache: cocoapods
xcode_workspace: Example/SlideMenuDovi.xcworkspace
xcode_scheme: SlideMenuDovi
xcode_sdk: iphonesimulator
podfile: Example/Podfile

before_install:
  - gem install bundler

after_success: slather

# language: objective-c
# osx_image: xcode7.3
#
# script: ./run_test.sh
